const logotipomenu = (prefix) => {
	return`┌───── •✧✧• ─────┐
                𝙇𝙤𝙜𝙤 ㊙️
└───── •✧✧• ─────┘
┏⬣
┃➤!wetglass
┃➤!multicolor3d
┃➤!watercolor
┃➤!luxurygold
┃➤!galaxywallpaper
┃➤!lighttext
┃➤!beautifulflower
┃➤!puppycute
┃➤!royaltext
┃➤!heartshaped
┃➤!birthdaycake
┃➤!galaxystyle
┃➤!hologram3d
┃➤!greenneon
┃➤!glossychrome
┃➤!greenbush
┃➤!metallogo
┃➤!noeltext
┃➤!glittergold
┃➤!textcake
┃➤!starsnight
┃➤!wooden3d
┃➤!textbyname
┃➤!writegalacy
┃➤!galaxybat
┃➤!snow3d
┃➤!birthdayday
┃➤!goldplaybutton
┃➤!silverplaybutton
┃➤!freefire
┃➤!blackpink
┃➤!neon
┃➤!greenneon
┃➤!advanceglow
┃➤!futureneon
┃➤!sandwriting
┃➤!sandsummer
┃➤!sandengraved
┃➤!metaldark
┃➤!neonlight
┃➤!holographic
┃➤!text1917
┃➤!minion
┃➤!deluxesilver
┃➤!newyearcard
┃➤!bloodfrosted
┃➤!halloween
┃➤!jokerlogo
┃➤!fireworksparkle
┃➤!natureleaves
┃➤!bokeh
┃➤!toxic
┃➤!strawberry
┃➤!box3d
┃➤!roadwarning
┃➤!breakwall
┃➤!icecold
┃➤!luxury
┃➤!cloud
┃➤!summersand
┃➤!horrorblood
┃➤!thunder
┗⬣`
}

exports.logotipomenu = logotipomenu